dist: bionic
language: python
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
  - 3.9
matrix:
  allow_failures:
  - python: 2.7
script:
  # Tests
  - python test_PDDL.py
  - python test_planner.py
  # Examples
  - python action.py
  - python PDDL.py    examples/dinner/dinner.pddl examples/dinner/pb1.pddl
  - python planner.py examples/dinner/dinner.pddl examples/dinner/pb1.pddl
  - python planner.py examples/airport/airport.pddl examples/airport/pb1.pddl