name: build
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9, '3.10']
      fail-fast: false
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    # Tests
    - run: python test_PDDL.py
    - run: python test_planner.py
    # Examples
    - run: python action.py
    - run: python PDDL.py    examples/dinner/dinner.pddl examples/dinner/pb1.pddl
    - run: python planner.py examples/dinner/dinner.pddl examples/dinner/pb1.pddl